import 'bootstrap/js/dist/util'
import 'bootstrap/js/dist/dropdown'
import 'bootstrap/js/dist/collapse'
// import 'bootstrap-select'
// import 'slick-carousel/slick/slick'
// import 'parsleyjs/dist/parsley'
import 'modules/UserAgent'
import 'modules/Menu'
