import 'bootstrap/js/dist/util'
import 'bootstrap/js/dist/dropdown'
import 'bootstrap/js/dist/collapse'
// import 'bootstrap-select'
import 'slick-carousel/slick/slick'
import 'parsleyjs/dist/parsley'
import 'modules/UserAgent'
// import 'modules/Counter'
import 'modules/Header'
import 'modules/FixHeight'
import 'modules/Menu'
import 'modules/FullPage'
import 'modules/FormAnim'
import 'modules/Faq'
import 'modules/TabBenefits'
import 'modules/Contact'
import 'modules/SignUp'
import 'modules/Login'
